// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/luchojuarez/call-sorter/internal/domain/ingestdata (interfaces: CallRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	callservice "github.com/luchojuarez/call-sorter/internal/infrastructure/callservice"
)

// MockCallRepository is a mock of CallRepository interface.
type MockCallRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCallRepositoryMockRecorder
}

// MockCallRepositoryMockRecorder is the mock recorder for MockCallRepository.
type MockCallRepositoryMockRecorder struct {
	mock *MockCallRepository
}

// NewMockCallRepository creates a new mock instance.
func NewMockCallRepository(ctrl *gomock.Controller) *MockCallRepository {
	mock := &MockCallRepository{ctrl: ctrl}
	mock.recorder = &MockCallRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallRepository) EXPECT() *MockCallRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockCallRepository) Save(arg0 context.Context, arg1 callservice.Model) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCallRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCallRepository)(nil).Save), arg0, arg1)
}
